apiVersion: v2
name: nalej-service-registry-webservice-fixture
description: Minimal web service used to verify Nalej Service Registry GitHub deployments
type: application
version: 0.1.0
appVersion: "14c26670"
