image:
  repository: public.ecr.aws/docker/library/node
  tag: "22-alpine"
  digest: sha256:76789712cd1ae89a1225eac9077010d68987a423588042dac30446f502f1858c
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi
